@extends('layouts.app')
@section('title', __('app.att.corrections'))
@section('content')
<section class="page-heading compact"><div><span class="eyebrow">{{ __('app.attendance') }}</span><h1>{{ __('app.att.corrections') }}</h1><p>{{ __('app.att.corrections_intro') }}</p></div><div class="table-actions"><a class="primary-button" href="{{ route('attendance.corrections.create') }}">{{ __('app.att.add_correction') }}</a><a class="ghost-button" href="{{ route('attendance.index') }}">{{ __('app.att.back_to_log') }}</a></div></section>
@include('partials.flash')
<div class="mini-stats"><div class="mini-stat accent"><span class="mini-stat-label">{{ __('app.att.pending_approval') }}</span><strong class="mini-stat-value">{{ $pendingCount }}</strong></div></div>
<section class="panel filter-panel"><form class="filter-bar" method="GET"><select name="company_id"><option value="">{{ __('app.all_companies') }}</option>@foreach($companies as $company)<option value="{{ $company->id }}" @selected((string)request('company_id')===(string)$company->id)>{{ $company->localizedName() }}</option>@endforeach</select><select name="status"><option value="">{{ __('app.all_statuses') }}</option>@foreach(['pending','approved','rejected'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ __('app.att.correction_'.$status) }}</option>@endforeach</select><button class="primary-button">{{ __('app.filters') }}</button></form></section>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>{{ __('app.att.employee') }}</th><th>{{ __('app.att.original_punch') }}</th><th>{{ __('app.att.requested_change') }}</th><th>{{ __('app.att.correction_reason') }}</th><th>{{ __('app.status') }}</th><th>{{ __('app.actions') }}</th></tr></thead><tbody>
@forelse($corrections as $correction)<tr><td><a class="cell-name" href="{{ route('employees.show',$correction->employee) }}">{{ $correction->employee->localizedName() }}</a><small>{{ $correction->requester->name }}</small></td><td dir="ltr">{{ $correction->original_punch_at?->format('Y-m-d h:i A') ?? __('app.att.new_punch') }}</td><td dir="ltr"><strong>{{ $correction->requested_punch_at->format('Y-m-d h:i A') }}</strong><small>{{ __('app.att.punch_'.$correction->requested_punch_type) }}</small></td><td class="correction-reason">{{ $correction->reason }}</td><td><span class="status-badge {{ $correction->status==='approved'?'success':($correction->status==='rejected'?'muted':'warning') }}">{{ __('app.att.correction_'.$correction->status) }}</span>@if($correction->reviewer)<small>{{ $correction->reviewer->name }}</small>@endif</td><td>
@if($correction->status==='pending')<div class="correction-actions"><form method="POST" action="{{ route('attendance.corrections.approve',$correction) }}">@csrf @method('PUT')<input name="review_notes" placeholder="{{ __('app.att.review_notes_optional') }}"><button class="primary-button">{{ __('app.att.approve') }}</button></form><form method="POST" action="{{ route('attendance.corrections.reject',$correction) }}">@csrf @method('PUT')<input name="review_notes" required placeholder="{{ __('app.att.rejection_reason') }}"><button class="danger-button">{{ __('app.att.reject') }}</button></form></div>
@else <span class="muted-note">{{ $correction->review_notes ?: __('app.none') }}</span>@endif
</td></tr>@empty<tr><td colspan="6" class="empty-row">{{ __('app.att.no_corrections') }}</td></tr>@endforelse
</tbody></table></div>{{ $corrections->links() }}</section>
@endsection
